### ISSUE TITLE
Necesito que prueben si funciona el link

### ISSUE THREAD

**Issue by PedroRamosRguez** [ULL-ESIT-GRADOII-DSI/localstorage-jquery-underscore-express-sass-heroku-rafa-pedro-dani#2]
@Rafaherrero @DanielRamosAcosta  necesito que me confirmeis  si funciona el link https://pdsi.herokuapp.com/  ya que a mi se me ve en blanco

**Comment by DanielRamosAcosta** [comment]
@alu0100505078 creo que es porque Heroku no está haciendo `bower install` después de decargar el repo.

**Comment by PedroRamosRguez** [comment]
@DanielRamosAcosta ya funciona, ahora el error es cargando el css solo 
gracias

**Comment by Rafaherrero** [comment]
Va perfecto!
